sudo: required
notifications:
email: false
language: java
jdk:
- oraclejdk8
before_install:
- sudo add-apt-repository ppa:dns/gnu -y
- sudo apt-get update -qq
install:
- sudo apt-get install -y --force-yes autoconf dos2unix icoutils xsltproc
script:
- tools/build-IrpTransmogrifier.sh
- tools/build-Girr.sh
- tools/build-Jirc.sh
- tools/build-DevSlashLirc.sh
- tools/build-HarcHardwareBundle.sh
- tools/build-tonto.sh -n
- tools/get-jdk-tar.sh
- mvn install -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
- ls -l --si target
- tools/upload.sh target/*.zip target/IrScrutinizer-*AppImage target/*AppImage.zsync target/*.md5 target/*.sha1

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:ci-build)$/
